kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - "$PWD/data/esdata:/usr/share/elasticsearch/data"

logstash:
  image: logstash
  links:
    - elasticsearch
  volumes:
    - "$PWD/config/logstash/:/config-dir"
    - "$PWD/data/logs:/usr/share/logstash/logs"
  command: logstash -f /config-dir/logstash.conf -l /usr/share/logstash/logs

